# Site settings
# in the templates available like {{ site.myvariable }}.
title: Art Teacher
email: megsadiq@gmail.com
brand: Megan Sadiq
headline: Artist, Teacher and More.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: megsadiq@gmail.com
phone: +1-740-274-8788

# Tracking
googleAnalitycsID: UA-83933844-1

